@startuml
entity ModelComponent << trait >> {
  type Model
  var model: Model
}
entity ViewComponent << trait >> {
  type View
  val view: View
}
entity UpdateComponent << trait >> {
  type Update
  val update: Update
}
entity MVU << trait >>
note left: Mixed-in with the components


ModelComponent <|-- MVU
ViewComponent <|-- MVU
UpdateComponent <|-- MVU

@enduml
