name: Satify CI Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ "main", "develop", "release/**" ]

  # to manually trigger a workflow on GitHub
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    # run on ubuntu, windows and macOS
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        run: sbt test

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Check scalafmt formatting
        run: sbt scalafmtCheckAll
