name: Satify ScalaDoc

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - develop

permissions:
  contents: write

jobs:
  scaladoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ GITHUB_HEAD_REF }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Create ScalaDoc
        run: sbt doc

      - name: Commit and push updated ScalaDoc
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "docs: Update ScalaDoc"
